### ISSUE TITLE
Trojan Win32/Sabsik.FL.Alml 

### ISSUE THREAD

**Issue by Notorious2Beat** [exislow/tidal-dl-ng#112]
### What happened?

Newest update v0.14.0 showing as a virus on Windows . Windows defender saying tidal-dl-ng exe is a virus.  Saying it's Trojan Win32/Sabsik.FL.Alml

### Version App

0.14.0

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
Uuuu
```

**Comment by exislow** [comment]
Thanks for this information. Here you can see the whole changelog: https://github.com/exislow/tidal-dl-ng/compare/v0.13.2...v0.14.0

I cannot detect any trojan code :D I do not know what to do about this message. You should probably get a proper AV ;D

**Comment by NoDowt** [comment]
Defender is actually fairly decent these days.

Running Win11 23H2 with latest Defender definitions here, latest release (15.2 exe version) does not get detected for me.
Smartscreen did flag it as its an uncommon file, but no virus detections.

VirusTotal does find a couple AV's reporting malware detections, however I suspect this is likely due to having some shared python code or similar behavior to actual malware.
