### ISSUE TITLE
[Bug] Tidal-Downloader-NG.exe is flagged as a malware on Windows

### ISSUE THREAD

**Issue by thr-4** [exislow/tidal-dl-ng#121]
### What happened?

Since this week, the executable file is flagged as "Trojan:Win32/Wacatac.B!ml" on Windows with a "Severe" threat level warning ("This program is dangerous and executes commands from an attacker."). The file can no longer be executed.

### Version App

v0.15.3

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
N/A
```

**Comment by thr-4** [comment]
![image](https://github.com/exislow/tidal-dl-ng/assets/90678880/4592f4bb-0fc3-48b5-9662-760c9679e1a6)

**Comment by MusicLover24** [comment]
I'd say this is a false-positive since the major AV softwares don't show it in scans.

**Comment by thr-4** [comment]
> I'd say this is a false-positive since the major AV softwares don't show it in scans.

Yes, that’s likely, but the implication is that it’s not even possible to run the app on Windows anymore - Defender deletes it automatically now.

**Comment by exislow** [comment]
Duplicate #112 

It is definitely a false positive. But I am also the developer, so who am I to trust? ;D But please do a code review by yourself and also compile the app by yourself. You will see it is a false positive. I cannot tell you why Windows Defender flags it like this. I suggest to disable Windows Defender and use a proper AV. Just let the file check here and decide for yourself: http://virustotal.com/

Since I am not a Windows user and have only limited know how about Windows Defender I cannot help in this case. But I am happy for any workaround as pull request.
