### ISSUE TITLE
[Feature] Create a proper folder structure to organise tracks which would be on multiple CDs

### ISSUE THREAD

**Issue by CodeMasterBlast** [exislow/tidal-dl-ng#151]
### Current Situation

Currently when you download an album which might be a 2 CD set all the tracks are bundled into one folder.

e.g.

   Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/ed2b1395-08c0-42c5-923f-c3bd55979c6a)

As you can see there are two track 1s and two track 2s etc, if this was presented on a physical format - CD it will be on CD1 and CD2.

### Suggestion / Feature Request

Check to see if an album has multiple tracks which should be put in their own folders, To closely organise the files  e.g. CD1, CD2, CD3 etc.

 Albums/{album_artist}/{album_title}{album_explicit}/CD1/{album_track_num}. {artist_name} - {track_title}

 Albums/{album_artist}/{album_title}{album_explicit}/CD2/{album_track_num}. {artist_name} - {track_title}

folder CD1 & CD2 under {album_title}{album_explicit} folder structure.

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/08fb90aa-3ff0-4413-99c2-86514d9e018e)

CD1 folder will contain-

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/4f581751-db3c-48e1-b1ed-1aa35111e224)

CD2 folder will contain-

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/bf2fc687-242d-47dd-aeba-4260eb88ac9f)

In essence the folder structure looks like-

Album
   Artist Name
      Album title
      Album title 2
      Album title 3
      Album title n 

Album
   Artist Name 2
      Album title
      Album title 2
      Album title 3
      Album title n 
etc

Under each album title folder will have CD1, CD2, CDn (this is optional only if there should be multiple CDs. If not then have the tracks under the Album title.)

Note: n denotes nth title for the artist.

**Comment by exislow** [comment]
Do you refer to this already implemented feature? #90

**Comment by CodeMasterBlast** [comment]
Hi,

I was going through the previous issues must of missed this one.

This kind of addresses the issue however the problem with this is it will always create '1' as a folder under album name even if there is only one CD. Ideally you only want to have the numbering appear if there is multiple CDs for the album e.g. CD1, CD2...

I was looking here-

https://github.com/exislow/tidal-dl-ng/blob/17390cba7c8276bef5b91f93eca0957ba7e9cbee/tidal_dl_ng/helper/path.py#L151

This

result = str(media.volume_num)

Always brings back 1, therefore in the 

"format_album": "Albums/{album_artist}/[{track_quality}{album_explicit}] {album_title}- [{album_id}] [{album_year}]/{track_volume_num}/{album_track_num} - {artist_name} - {track_title}"

This will have '1' created as a folder under album title and all the tracks will be listed under this folder.

Ideally what is required is

-some how to determine the max

                                    result = str(media.volume_num)

Find out how many iterations (number of CDs under album title) max (result) if it is > 1 then add a value to 'track_volume_num' variable starting with '1' (CD1)  else leave it as NULL.

e.g.
   
    Find out number of CDs that the album has

pseudo code-

    IF CDs=1 THEN
      track_volume_num IS NULL;
     result=track_volume_num; --(doesn't create the '1' folder under album title folder)
   ELSE
       FOR x=1 to Number of CDs

         track_volume_num=CD||x  --(concatenate text CD with CD number (x))
         
        result=track_volume_num --(send back CD1, CD2 etc)
       END FOR LOOP
    END IF;


In directory structure where only one CD is present just tracks are listed under album title  (track_volume_num IS NULL)

<Album name>
      track 1
      track 2
      track 3

In directory structure which has multiple CDs  --(CD1, CD2 etc)

<Album name>
       <CD1>
            track 1
             track 2
              track 3
              ...
        <CD2>
             track 1
              track 2
               track 3
              ...
       <CD3>
            track 1
             track 2
              track 3
              ....

Hope I've explained it properly,

**Comment by exislow** [comment]
I will try to implement an optional volume placeholder.

**Comment by exislow** [comment]
Fixed with https://github.com/exislow/tidal-dl-ng/commit/ce02215d7cbf8d05998985b129adef7694bf9c1e

You are looking for this tag `{track_volume_num_optional_CD}`

**Comment by passat1** [comment]
When using {track_volume_num_optional_CD}, all tracks, except from **last volume**, are correctly placed in sub-folders CD1, CD2, ... CDn-1.
Where 'n' is total number of volumes.
But all tracks from **last volume** 'n' do not have their folder CDn, but they are placed directly inside '{album_artist} - {album_title}{album_explicit}' folder.
So, last volume folder (CDn) is missing.
It seems that problem is because folders are not created `result = "" if media.volume_num is num_volumes` but it should be **only if** 'num_volumes = 1', otherwise, when 'media.volume_num' reaches last number 'num_volumes', 'result' becomes "" (empty) and folder is not created.
Sorry, but this need some small corrections to be completely solved.

**Comment by exislow** [comment]
You are right. Thanks for reporting this. I have fixed it with https://github.com/exislow/tidal-dl-ng/commit/ccbb1f246c01aeaa1c20864453cb55d31b9c7069

Will be released soon.

**Comment by hightower1974** [comment]
Please help, what should I set for the album? Because with this setting, it creates separate albums for each disc. I would like it to be in 1 directory, with multiple discs in separate folders. Thanks.

Albums/{album_artist} - {album_title}{album_explicit} {track_volume_num_optional_CD} {album_year}/{album_track_num}. {artist_name} - {track_title}

**Comment by passat1** [comment]
Yes, because you have put '{track_volume_num_optional_CD}' INSIDE (as part of) your album name.
So, different name -> different folder.
It should be set as '**separate sub-folder**' of whatever you wish to be your album name, for example:
`Albums/{album_artist} - {album_title}{album_explicit} {album_year}/{track_volume_num_optional_CD}/{album_track_num}. {artist_name} - {track_title}`

**Comment by hightower1974** [comment]
Thanks. This perfect "
Albums/{album_artist} - {album_title}{album_explicit} {album_year}/{track_volume_num_optional_CD}/{album_track_num}. {artist_name} - {track_title}"

**Comment by hightower1974** [comment]
There is only one problem that needs to be fixed somehow, that a lot of classical music works have very long file names, album + track, exceeding 259 characters and need to be downloaded as separate tracks, not such a problem, but can't this be fixed somehow to shorten such long track names? Tidal gui does this wonderfully.

**Comment by exislow** [comment]
Please create a separate issue for this and be a precise with all details and steps necessary for re-production as possible.
