### ISSUE TITLE
[Help] I'm getting oddly different file sizes in different devices

### ISSUE THREAD

**Issue by merundium** [exislow/tidal-dl-ng#178]
### I need Help.

Hi guys,

As the title says i'm getting size discrepancies (some MBs) in the resulting files using two different devices, same tracks, same settings in both. I'm using termux in Android and I've been unable to figure out what's the issue, something is adding (or removing) some data.

I picked these tracks just as example:

https://tidal.com/browse/track/1781892?u
https://tidal.com/browse/track/1781812?u
https://tidal.com/browse/track/1781861?u

Device 1:
<img width="310" alt="termux1" src="https://github.com/user-attachments/assets/b44fecd6-5ec2-4e68-af04-e61703008936">
Device 2:
![termux2](https://github.com/user-attachments/assets/e0fc4fb8-e4a3-4c9e-b5ec-8adbd335d9aa)

Maybe some of you can download the same tracks and tell me what sizes you are getting for the resulting files.

Thank you.

### What operating system are you seeing the problem on?

None

### Your settings

```json
{"skip_existing": "false", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "/data/data/com.termux/files/home/storage/music", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "/data/data/com.termux/files/usr/bin/ffmpeg", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by WinFan3672** [comment]
The difference is most likely the way devices differentiate between megabytes and mebibytes. Confused? Not surprising. A megabyte is 1000 kilobytes, which is 1000 bytes. A mebibyte is 1024 kibibytes, which is 1024 bytes. The former is correctly represented as MB and the latter as MiB. 

However, the annoying thing is that many programs (including Windows) report mebibytes (because the powers of two thing makes it much easier to do math on) as MB and not MiB, whereas some correctly report megabytes as MB. 

The result of this insanity is what you are witnessing. If you check exactly how many bytes each file is, it should be identical. If not, it's a TIDAL problem.
