### ISSUE TITLE
[Bug] Fake bitrate?

### ISSUE THREAD

**Issue by BobDobolina** [exislow/tidal-dl-ng#191]
### What happened?

Fakin' the Funk reports that the bit rates are fake for albums I download. I've tried downloading in high_lossless, hi_res, and hi_res_lossless with the same result.  The tracks show lossless bit rates, but Fakin' the Funk reports that the actual bit rates are 320kbps quality. I'm on a Tidal Family subscription with audio quality set at Max.

![Funk report](https://github.com/user-attachments/assets/744accf3-d9c7-4a44-9e14-8430c103a633)
.

### Version App

v0.15.6

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": true, "lyrics_file": false, "video_download": false, "download_delay": false, "download_base_path": "C:\\Users\\rsdk3\\Downloads\\1 - Tidal downloads", "quality_audio": "LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "C:\\Users\\rsdk3\\Downloads\\TIDAL-Downloader-NG_windows-x64\\TIDAL-Downloader-NG\\ffmpeg\\ffmpeg.exe", "metadata_cover_dimension": "1280", "extract_flac": false, "downgrade_on_hi_res": false}
```

**Comment by IJWTU12** [comment]
Use the program called Spek to check Highest Frequency of the track to see if it lossless or not. Here is the ratio of cut off frequency chart. The Program you are using may not be accurate as this one because i remember using it on lossless it says lossless but when i compressed it down to mp3 320 kbps it's still says lossless
![02  Eagles - Witchy Woman (2013 Remaster) flac](https://github.com/user-attachments/assets/d35e1261-7564-4f7c-b122-bafc859b025d)
bit rate cut-off frequency compression
1411kbps >20kHz 1:1
320kbps 19.5kHz 1:4.4
192kbps 18kHz 1:7.3
160kbps 17kHz 1:8.8
128kbps 16kHz 1:11
96kbps 15kHz 1:14.7
64kbps 11kHz 1:22
32kbps 5kHz 1:44
The frequency may varies because of the recording process is not up to in sometimes. Example, one track i download is not record properly and even though Tidal says it's High which should be lossless but the frequency cut off at 15 kHz which equal as the record that were made in 1970's and below. Looking at the cut-off frequency in Spek is most accurate way to check if it's  lossless or not and by the way please check this extract flac box and download it again (Don't forget to install the ffmpeg first and locate the ffmpeg path in the program) because the program may misunderstand the format that have been downloaded without checking this box as lossy format even though not checking this box is still no cut-off in frequency in Spek and if you compared the not checking the extract flac box and checking the extract flac box in Spek it's still the same. Thank you for reading.
![Screenshot (32)](https://github.com/user-attachments/assets/779d2130-94d5-4489-b184-c32054f30c29)

And another thing is how to install ffmpeg in windows. First go to this website https://www.gyan.dev/ffmpeg/builds/
and download the Full version 
![Screenshot (34)](https://github.com/user-attachments/assets/1803f356-45fc-4580-a1ed-947af887324f)
extract the zip/rar and then go to Environment Variables click Path and Edit and new window will pops like in the picture and click new then locate the extract ffmpeg like in the picture
![Screenshot (35)](https://github.com/user-attachments/assets/64c18de9-f3db-4341-882c-4b4c86e37c15)
and then locate the path again in the program in option path_binary_ffmpeg but this time you choose the ffmpeg.exe instead of the bin folder.

**Comment by BobDobolina** [comment]
Thanks. I'll look into Spek because otherwise I don't know where the problem lies. I made the changes you recommended and then downloaded several albums through tidal-dl-ng. Three of the albums showed wrong bit rates for all tracks under Fakin' the Funk, but there was one (the Beatles' Abbey Road, 2009 remastered) that was fine. The problem could be with Fakin' the Funk but could also be with Tidal itself and its processing of tracks for download.

**Comment by ottworks** [comment]
I've come across this before. The label simply opted to upload a low quality file to tidal, if you were to record the output of tidal you'd find the same result.
