### ISSUE TITLE
[Feature] Album ID as a formatting variable

### ISSUE THREAD

**Issue by daylight-00** [exislow/tidal-dl-ng#85]
### Current Situation

The album ID is not supported as a formatting variable.

### Suggestion / Feature Request

In managing albums with duplicate names, having an album ID in the formatting variables would be beneficial.

**Comment by daylight-00** [comment]
Additionally, it would be nice to be able to reference the album id or album year of a track even when entering a track.

**Comment by exislow** [comment]
Can you just provide clear examples how do you imagine this features? Just provide a placeholder string and a possible outcome after the file was downloaded.

**Comment by daylight-00** [comment]
Thanks for reply. Here's an example while downloading single track below.
[https://tidal.com/browse/track/245042543?u](url)

Placeholder String:
`"format_track": "./{album_artist} - {album_title} [{album_year}] [{album_id}]/{album_track_num} - {track_title} [{track_id}]"`

Desired Output:
`~/Childish Gambino - Awaken, My Love! [2016] [245042543]/06 - Redbone [245042535].m4a`

**Comment by motlaghreyhan** [comment]
I'm pretty sure album_year already works. At least it does for me. You can see a list of variables [here](https://github.com/exislow/tidal-dl-ng/blob/7b096bcf8443ab652817cc9da3e5dba03a5dc363/tidal_dl_ng/helper/path.py#L123).


Not sure if this warrants it's own issue, but I think some sort of sort by CD/volume sorting is important as well. For example if you download this [link](https://tidal.com/browse/album/118390427?u) (or really any "Deluxe" version of an album), you get a bunch of duplicate track numbers because it's not sorted by volume. There seems to be a volume_num variable that shows up somewhere, but I can't get it to work in the cfg file.

**Comment by exislow** [comment]
From the next release on you can use `album_year` within track namings as well. `album_id` can be used to retrieve the album's ID.

> Not sure if this warrants it's own issue, but I think some sort of sort by CD/volume sorting is important as well. For example if you download this [link](https://tidal.com/browse/album/118390427?u) (or really any "Deluxe" version of an album), you get a bunch of duplicate track numbers because it's not sorted by volume. There seems to be a volume_num variable that shows up somewhere, but I can't get it to work in the cfg file.
> 
> My tidal-dl configs were `albumFolderFormat": "{ArtistName}/{Flag} {AlbumTitle} [{AlbumID}] [{AlbumYear}]"` and `"trackFileFormat": "{TrackNumber} - {ArtistName} - {TrackTitle}{ExplicitFlag}",`

I do not really get what you like to achieve, since the versions ("Deluxe" etc.) are already part of the album name. Can you provide an example (placeholders and the result after all variables have been replaced)? Also please provide the API variables, where to find the data you like to actually get as a value for the naming variables. 

Please open a new issue for that.

**Comment by daylight-00** [comment]
Sometimes albums are not distinguished by edition markings (especially for singles and EPs).

[](url)https://listen.tidal.com/album/97482881
[](url)https://listen.tidal.com/album/37563634
[](url)https://listen.tidal.com/album/37563697

For example, if you download an album from these links, the files will be overwritten because the album name and some of the track names are exactly the same, even though they are organized slightly differently. Unfortunately, I don't know much about the TIDAL API :(

**Comment by exislow** [comment]
In this case use `album_num_tracks` as an album placeholder for replacement.
